import { createCelestialBody } from "./creators.js";

const celestialBodiesData = [
  {
    name: "sun",
    label: "Sol",
    size: 12,
    texture: "textures/8k_sun.jpg",
    baseRotation: 0.001,
  },
  {
    name: "mercury",
    label: "Mercúrio",
    size: 1.5,
    texture: "textures/8k_mercury.jpg",
    radius: 35,
    speed: 1.6,
    baseRotation: 0.008,
  },
  {
    name: "venus",
    label: "Vênus",
    size: 2.5,
    texture: "textures/8k_venus_surface.jpg",
    radius: 50,
    speed: 1.2,
    baseRotation: 0.003,
  },
  {
    name: "earth",
    label: "Terra",
    size: 2.6,
    texture: "textures/8k_earth_daymap.jpg",
    radius: 68,
    speed: 1.0,
    baseRotation: 0.05,
    moons: [
      {
        texture: "textures/8k_moon.jpg",
        size: 0.6,
        baseRotation: 0.02,
        radius: 5,
        speed: 0.3,
      },
    ],
  },
  {
    name: "mars",
    label: "Marte",
    size: 2,
    texture: "textures/8k_mars.jpg",
    radius: 85,
    speed: 0.8,
    baseRotation: 0.052,
  },
  {
    name: "jupiter",
    label: "Júpiter",
    size: 7,
    texture: "textures/8k_jupiter.jpg",
    radius: 120,
    speed: 0.4,
    baseRotation: 0.12,
    moons: [
      {
        label: "Europa",
        texture: "textures/europa.jpg",
        size: 0.4,
        baseRotation: 0.01,
        radius: 13,
        speed: 0.8,
      },
      {
        label: "Callisto",
        texture: "textures/callisto.jpg",
        size: 0.5,
        baseRotation: 0.01,
        radius: 19,
        speed: 0.4,
      },
      {
        label: "Ganymedes",
        texture: "textures/ganymede.jpg",
        size: 0.5,
        baseRotation: 0.01,
        radius: 15,
        speed: 0.7,
      },
      {
        label: "IO",
        texture: "textures/io.png",
        size: 0.7,
        baseRotation: 0.01,
        radius: 11,
        speed: 1,
      },
    ],
  },
  {
    name: "saturn",
    label: "Saturno",
    size: 6,
    texture: "textures/8k_saturn.jpg",
    radius: 160,
    speed: 0.3,
    baseRotation: 0.11,
    ring: { texture: "textures/8k_saturn_ring_alpha.png" },
  },
  {
    name: "uranus",
    label: "Urano",
    size: 4,
    texture: "textures/2k_uranus.jpg",
    radius: 200,
    speed: 0.2,
    baseRotation: 0.08,
  },
  {
    name: "neptune",
    label: "Netuno",
    size: 3.8,
    texture: "textures/2k_neptune.jpg",
    radius: 240,
    speed: 0.15,
    baseRotation: 0.07,
    moons: [
      {
        label: "Triton",
        texture: "textures/triton.jpg",
        size: 0.4,
        baseRotation: 0.001,
        radius: 12,
        speed: 0.7,
      },
    ],
  },
];

// Processa os dados brutos para criar os objetos 3D
export const celestialBodies = celestialBodiesData.map((data) =>
  createCelestialBody(data)
);
